"""ajusta schema dos models

Revision ID: b1b83a127175
Revises: 345e84a68ee5
Create Date: 2026-09-29 12:53:27.224805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b83a127175'
down_revision: Union[str, None] = '345e84a68ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually! ###
    # Ajustes manuais: tamanhos de String, CHECK constraints de CPF/CNPJ e
    # server_default do timestamp (o autogenerate não detecta essas mudanças).
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_categories_description'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=14),
               nullable=False)
        batch_op.create_check_constraint('ck_clients_cnpj_length', 'length(cnpj) = 14')
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Enum('JUNIOR', 'PLENO', 'SENIOR', 'ADMIN', name='ck_employees_level', native_enum=False, length=20, create_constraint=True), server_default='JUNIOR', nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=11),
               nullable=False)
        batch_op.create_check_constraint('ck_employees_cpf_length', 'length(cpf) = 11')
        batch_op.drop_index(batch_op.f('ix_employees_id'))

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('table',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('performed_by',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               server_default=sa.func.now(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_logs_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_id'), ['id'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('performed_by',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('table',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)
        batch_op.drop_constraint('ck_employees_cpf_length', type_='check')
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('ck_employees_level', type_='check')
        batch_op.drop_column('level')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.drop_constraint('ck_clients_cnpj_length', type_='check')
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_description'), ['description'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
