"""adiciona senha do funcionario

Revision ID: e7c67ab5ceea
Revises: b1b83a127175
Create Date: 2026-09-29 13:26:18.128061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c67ab5ceea'
down_revision: Union[str, None] = 'b1b83a127175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # A coluna é NOT NULL sem valor padrão: só roda com a tabela employees vazia.
    # Com funcionários já cadastrados, seria preciso definir uma senha para cada um.
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
